<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxaoSDU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxaoSDU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxaoSDU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxaoSDU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUxaoSDU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UxaoSDU',
    'container.build_id' => 'b324b3dc',
    'container.build_time' => 1645597393,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxaoSDU');
